import homepage from './homepage.jpg'
import home from './home.jpg'
import homee from './homee.jpg'


export const data = [
  {
      "id": 1,
      "name": "Havana",
      "material": "Gold",
      "type": "Bracelet",
      "price": 99.00,
      "stock": 5,
      "image": home,
  },
  {
      "id": 2,
      "name": "Leaf",
      "type": "Necklace",
      "material": "Silver",
      "price": 42.00,
      "stock": 4,
      "image": homee,
  },
  {
      "id": 3,
      "name": "Kira",
      "type": "Ring",
      "material": "Platinium",
      "price": 34.00,
      "stock": 12,
      "image": homepage,
  },
  {
      "id": 4,
      "type": "Buckle",
      "name": "Rainbow",
      "material": "Diamond",
      "price": 19.00,
      "stock": 6,
      "image": home,
  },
  {
      "id": 5,
      "type": "Necklace",
      "name": "Fifi",
      "material": "Emerald",
      "price": 19.00,
      "stock": 0,
      "image": homee,
  },
  {
      "id": 6,
      "type": "Bracelet",
      "material": "Pearl",
      "name": "Bold",
      "price": 167.00,
      "stock": 6,
      "image": homepage,
  },
  {
      "id": 7,
      "name": "Cara",
      "type": "Ring",
      "material": "Ruby",
      "price": 30.00,
      "stock": 5,
      "image": home,
  },
  {
      "id": 8,
      "name": "Vahana",
      "type": "Buckle",
      "material": "Gold",
      "price": 49.99,
      "stock": 9,
      "image": home,
  },
  {
      "id": 9,
      "name": "Shirley",
      "type": "Bracelet",
      "material": "Silver",
      "price": 49.99,
      "offer": 39.99,
      "stock": 9,
      "image": homee,
  },
  {
      "id": 10,
      "name": "Sprinkle",
      "type": "Necklace",
      "material": "Platinium",
      "price": 75.00,
      "stock": 2,
      "image": homepage,
  },
  {
      "id": 11,
      "name": "Didi",
      "type": "Ring",
      "material": "Diamond",
      "price": 175.50,
      "stock": 1,
      "image": home,
  },
  {
      "id": 12,
      "name": "Prya",
      "type": "Buckle",
      "material": "Emerald",
      "price": 270.00,
      "stock": 10,
      "image": homee,
  },
  {
      "id": 13,
      "name": "Ceecee",
      "type": "Bracelet",
      "material": "Pearl",
      "price": 540.00,
      "stock": 5,
      "image": homepage,
  }
]